name: Deploy DSA-Bible

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Reset the commit history
        run: |
          git checkout --orphan orphan
          git add --all
          git config user.name "akhilub"
          git config user.email $EMAIL
          git commit -m 'Update DSA-Bible content'
          git branch -D main
          git branch -m main
          git push origin main -f
        env:
          EMAIL: ${{ secrets.EMAIL }}
